# Generated by Django 5.0.6 on 2024-09-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Study',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='study_description',
            new_name='student_description',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='study_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='study_phase',
            new_name='student_phase',
        ),
    ]
